/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Zhang Jiacheng										   *
************************************************************************
* Object        : 
* Module        : 
* Instance      : 
* Description   : 
*-----------------------------------------------------------------------
* Version: 
* Date: 
* Author: 
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date           Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jun 02,2016                         Initial version
*----------------------------------------------------------------------
* 0.2         Jan 13,2017    ShangQiuju     Fix Coverity warning.
*----------------------------------------------------------------------
* 0.3         Apr 01,2017    Pei Jingli         Remove static interfaces.
*=====================================================================*/
#ifndef _FIFO_H_
#define _FIFO_H_ 
#include "Define.h"
/**** Definition of constants ****/


/**** Definition of types ****/ 

/**** Definition of macros ****/


/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/

#endif /*_FIFO_IF_H_*/

/****************************** END OF FILE ***************************/
