/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   :            										   *
************************************************************************
* Object        : 
* Module        : 
* Instance      : 
* Description   : 
*-----------------------------------------------------------------------
* Version: 
* Date: 
* Author: 
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1                                    Initial version
*-----------------------------------------------------------------------
* 0.2     Apr 1,2017  PEI Jingli Fix include files.
*=====================================================================*/
#ifndef _FIFO_U16_H_
#define _FIFO_U16_H_ 
#include "Define.h"

/**** Definition of constants ****/


/**** Definition of types ****/ 


/**** Definition of macros ****/


/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/
static BOOL fifo_u16_is_full(FIFO_U16_TYPE *this);


#endif /*_FIFO_U16_H_*/

/****************************** END OF FILE ***************************/

