/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        :
* Module        :
* Instance      :
* Description   :
* file: D:/AutoSar generated code/intvect_c0.c 
* automatically generated by genRH850.exe, Version: 1.06 
* Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil 
* Generation time: Mon May 16 10:20:54 2016 
* Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel 
* Implementation: RH850_D1M 
* Version of general code: 9.01.04 
*-----------------------------------------------------------------------
* Version:
* Date:
* Author:
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jan 02,2016    Initial version
*-----------------------------------------------------------------------
* 0.2	   Dec 20,2016   ShangQiuju Add config file according using hw.
*----------------------------------------------------------------------
* 0.3          Dec 21,2016    PEI Jingli    remove ds03h hw config,using test file instead of.
* ----------------------------------------------------------------------
* 0.4          Jan 05,2017    ZhangJie     Delete test code for NMI_TEST
* ----------------------------------------------------------------------
* 0.5          Jan 06,2017    ZhangJie     Repleace NMI exception handle function
* ----------------------------------------------------------------------
* 0.6          Feb 07,2017    ZhangJie     Change CAN ISR from channel 0 to 2.
*=====================================================================*/

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#include "core_cfg.h"

#pragma asm

   .align 512
   .section ".osExceptionVectorTable_c0", "ax"

   .globl _osExceptionVectorTable_c0   /* start of the core exception vector table */
_osExceptionVectorTable_c0:

   .offset 0x0000
   .globl _RESET
   jr _RESET

   .offset 0x0010
   .globl _osCoreException_c0_0x0010
_osCoreException_c0_0x0010:
   jr _osUnhandledCoreException

   .offset 0x0020
   .globl _osCoreException_c0_0x0020
_osCoreException_c0_0x0020:
   jr _osUnhandledCoreException

   .offset 0x0030
   .globl _osCoreException_c0_0x0030
_osCoreException_c0_0x0030:
   jr _osUnhandledCoreException

   .offset 0x0040
   .globl _osCoreException_c0_0x0040
_osCoreException_c0_0x0040:
   jr _osTrapDispatcher_c0

   .offset 0x0050
   .globl _osCoreException_c0_0x0050
_osCoreException_c0_0x0050:
   jr _osUnhandledCoreException

   .offset 0x0060
   .globl _osCoreException_c0_0x0060
_osCoreException_c0_0x0060:
   jr _osUnhandledCoreException

   .offset 0x0070
   .globl _osCoreException_c0_0x0070
_osCoreException_c0_0x0070:
   jr _osUnhandledCoreException

   .offset 0x0080
   .globl _osCoreException_c0_0x0080
_osCoreException_c0_0x0080:
   jr _osUnhandledCoreException

   .offset 0x0090
   .globl _osCoreException_c0_0x0090
_osCoreException_c0_0x0090:
   jr _osUnhandledCoreException

   .offset 0x00a0
   .globl _osCoreException_c0_0x00a0
_osCoreException_c0_0x00a0:
   jr _osUnhandledCoreException

   .offset 0x00b0
   .globl _osCoreException_c0_0x00b0
_osCoreException_c0_0x00b0:
   jr _osUnhandledCoreException

   .offset 0x00c0
   .globl _osCoreException_c0_0x00c0
_osCoreException_c0_0x00c0:
   jr _osUnhandledCoreException

   .offset 0x00d0
   .globl _osCoreException_c0_0x00d0
_osCoreException_c0_0x00d0:
   jr _osUnhandledCoreException

   .offset 0x00e0
   .globl _osCoreException_c0_0x00e0
_osCoreException_c0_0x00e0:
   jr _FENMIHandler

   .offset 0x00f0
   .globl _osCoreException_c0_0x00f0
_osCoreException_c0_0x00f0:
   jr _osUnhandledCoreException

   .offset 0x0100
   .globl _osCoreException_c0_0x0100
_osCoreException_c0_0x0100:
   jr _osUnhandledDirectBranchException

   .offset 0x0110
   .globl _osCoreException_c0_0x0110
_osCoreException_c0_0x0110:
   jr _osUnhandledDirectBranchException

   .offset 0x0120
   .globl _osCoreException_c0_0x0120
_osCoreException_c0_0x0120:
   jr _osUnhandledDirectBranchException

   .offset 0x0130
   .globl _osCoreException_c0_0x0130
_osCoreException_c0_0x0130:
   jr _osUnhandledDirectBranchException

   .offset 0x0140
   .globl _osCoreException_c0_0x0140
_osCoreException_c0_0x0140:
   jr _osUnhandledDirectBranchException

   .offset 0x0150
   .globl _osCoreException_c0_0x0150
_osCoreException_c0_0x0150:
   jr _osUnhandledDirectBranchException

   .offset 0x0160
   .globl _osCoreException_c0_0x0160
_osCoreException_c0_0x0160:
   jr _osUnhandledDirectBranchException

   .offset 0x0170
   .globl _osCoreException_c0_0x0170
_osCoreException_c0_0x0170:
   jr _osUnhandledDirectBranchException		/*test WDT0 NMI INT*/
	//jr	_priority7_interrupt

   
   .offset 0x0180
   .globl _osCoreException_c0_0x0180
_osCoreException_c0_0x0180:
   jr _osUnhandledDirectBranchException

   .offset 0x0190
   .globl _osCoreException_c0_0x0190
_osCoreException_c0_0x0190:
   jr _osUnhandledDirectBranchException

   .offset 0x01a0
   .globl _osCoreException_c0_0x01a0
_osCoreException_c0_0x01a0:
   jr _osUnhandledDirectBranchException

   .offset 0x01b0
   .globl _osCoreException_c0_0x01b0
_osCoreException_c0_0x01b0:
   jr _osUnhandledDirectBranchException

   .offset 0x01c0
   .globl _osCoreException_c0_0x01c0
_osCoreException_c0_0x01c0:
   jr _osUnhandledDirectBranchException

   .offset 0x01d0
   .globl _osCoreException_c0_0x01d0
_osCoreException_c0_0x01d0:
   jr _osUnhandledDirectBranchException

   .offset 0x01e0
   .globl _osCoreException_c0_0x01e0
_osCoreException_c0_0x01e0:
   jr _osUnhandledDirectBranchException

   .offset 0x01f0
   .globl _osCoreException_c0_0x01f0
_osCoreException_c0_0x01f0:
   jr _osUnhandledDirectBranchException

   .globl _osExceptionVectorTableEnd_c0
_osExceptionVectorTableEnd_c0:   /* end of the core exception vector table */

#pragma endasm

#pragma asm

   .align 512
   .section ".osEIINTVectorTable_c0", "ax"

   .globl _osEIINTVectorTable_c0   /* start of the EIINT exception vector table */
_osEIINTVectorTable_c0:
   .word _osUnhandledEIINTException   /* interrupt index = 0 */
   .word _ISR_TAUD0I2_CAT2  /* TAUD0I2 */         
   .word _osUnhandledEIINTException
   .word _ISR_TAUD0I6_CAT2 //_osUnhandledEIINTException INT=3
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_ADCA0_INTSG1_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_CANGERR_CAT2   /* interrupt index = 14 */
   .word _ISR_CANGRECC_CAT2 /* interrupt index = 15 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_CSIH0IC_CAT2				/* interrupt index = 21 */
   .word _ISR_CSIH0IR_CAT2                           /* interrupt index = 22 */
   .word _ISR_CSIH0IRE_CAT2                         /* interrupt index = 23 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_UART0_Tx_CAT2
   .word _ISR_UART0_Rx_CAT2
   .word _ISR_UART0_Error_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_WDTA0_CAT2   /* interrupt index = 32 */
   .word _osUnhandledEIINTException
   .word _ISR_INTP3_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_INTP10_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException	//_osUnhandledEIINTException  INT=42
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_TAUD0I15_CAT2   /* interrupt index = 46 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_IIC0TI_CAT2
   .word _ISR_IIC0TEI_CAT2
   .word _ISR_IIC0RI_CAT2
   .word _ISR_IIC0EE_CAT2
   .word _ISR_TAUJ0I0_CAT2   /* interrupt index = 72 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_OSTM0_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_CAN1ERR_CAT2   /* interrupt index = 105 */
   .word _osUnhandledEIINTException   /* interrupt index = 17 */
   .word _ISR_CAN1TRX_CAT2   /* interrupt index = 107 */
   .word _ISR_CSIH1IC_CAT2				//108,
   .word _ISR_CSIH1IR_CAT2				//109, SPI RX
   .word _ISR_CSIH1IRE_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_INTP6_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_TAUB0I0_CAT2   /* interrupt index = 134 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException        //139,TAUB0I5
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_TAUB0I11_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_UART2_Tx_CAT2   //157 uart2
   .word _ISR_UART2_Rx_CAT2
   .word _ISR_UART2_Error_CAT2
   .word _ISR_TAUJ1I0_CAT2   /* interrupt index = 160 */
   .word _osUnhandledEIINTException
   .word _ISR_TAUJ1I2_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException//170
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException//180
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException//190
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException//200
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException   /* interrupt index = 209 */
   .word _osUnhandledEIINTException   /* interrupt index = 210 */
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _ISR_UART3_Tx_CAT2
   .word _ISR_UART3_Rx_CAT2
   .word _ISR_UART3_Error_CAT2
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .word _osUnhandledEIINTException
   .globl _osEIINTVectorTableEnd_c0
_osEIINTVectorTableEnd_c0:   /* end of the EIINT exception vector table */

#pragma endasm

#pragma asm

   .section ".os_text", "ax"

   /* MISRA RULE 14.1 not violated: ISR_TAUD0I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUD0I15, 0) /* PRQA S 1503 */


	osCAT2ISRC0(ISR_IIC0RI,1)
	osCAT2ISRC0(ISR_IIC0TI,1)
	osCAT2ISRC0(ISR_IIC0TEI,1)
	osCAT2ISRC0(ISR_IIC0EE,1)
	osCAT2ISRC0(ISR_ADCA0_INTSG1,1)
	osCAT2ISRC0(ISR_CSIH1IC,1)	
	osCAT2ISRC0(ISR_CSIH1IR,1)
	osCAT2ISRC0(ISR_CSIH1IRE,1)
	
	osCAT2ISRC0(ISR_CSIH0IC,1)	
	osCAT2ISRC0(ISR_CSIH0IR,1)
	osCAT2ISRC0(ISR_CSIH0IRE,1)
	osCAT2ISRC0(ISR_UART0_Tx,1)
	osCAT2ISRC0(ISR_UART0_Rx,1)
	osCAT2ISRC0(ISR_UART0_Error,1)
	osCAT2ISRC0(ISR_OSTM0,1)

   osCAT2ISRC0(ISR_INTP10, 1) 
   osCAT2ISRC0(ISR_INTP6, 1)
   osCAT2ISRC0(ISR_INTP3, 1)

   osCAT2ISRC0(ISR_UART3_Tx,1)
   osCAT2ISRC0(ISR_UART3_Rx,1)
   osCAT2ISRC0(ISR_UART3_Error,1)

   
   /* MISRA RULE 14.1 not violated: ISR_CANGERR is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CANGERR, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_CANGRECC is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CANGRECC, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_CAN0ERR is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN1ERR, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_CAN0TRX is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN1TRX, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_WDTA0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_WDTA0, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUJ0I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUJ0I0, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUB0I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUB0I0, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUJ1I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUJ1I0, 1) /* PRQA S 1503 */

    osCAT2ISRC0(ISR_TAUD0I6, 1) /*26  TAUD0I1 */
    osCAT2ISRC0(ISR_TAUJ1I2, 1) /*27 TAUD0I2 */
    osCAT2ISRC0(ISR_TAUD0I2, 1) /*TAUD0I2*/
    osCAT2ISRC0(ISR_TAUB0I11, 1) /*TAUB0I11*/

	osCAT2ISRC0(ISR_UART2_Tx,1)	
	osCAT2ISRC0(ISR_UART2_Rx,1)
	osCAT2ISRC0(ISR_UART2_Error,1)

#pragma endasm

