/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        :
* Module        :
* Instance      :
* Description   :
* file: D:/AutoSar generated code/osConfigBlock.c 
* automatically generated by genRH850.exe, Version: 1.06 
* Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil 
* Generation time: Mon May 16 15:29:05 2016 
* Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel 
* Implementation: RH850_D1M 
* Version of general code: 9.01.04 
*-----------------------------------------------------------------------
* Version:
* Date:
* Author:
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jan 02,2016    Initial version
*-----------------------------------------------------------------------
* 0.2	   Dec 20,2016   ShangQiuju Add config file according using hw.
 ----------------------------------------------------------------------
* 0.3          Dec 21,2016    PEI Jingli    remove ds03h hw config,using test file instead of.
* ----------------------------------------------------------------------
* 0.4          Feb 07,2017    ZhangJie     Change CAN ISR from channel 0 to 2.
* ----------------------------------------------------------------------
* 0.5          Apr 13,2017    ZhangJie     Fix intp-isr.
*=====================================================================*/

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#pragma ghs section rodata=".os_rodata"
#pragma ghs section rosdata=".os_rosdata"

/* MISRA RULE 8.10 VIOLATION: osConfigBlock is accessed by several modules in many configurations.
*  Declaring this variable static in the other cases would increase code complexity too much.
*/
osqROM0 osqROM1 const osqROM2 tsConfigBlock osqROM3 osConfigBlock = /* PRQA S 1504 */ 
{
   /* Frame */
   {0x82, 0x2A, 0x0C, 0xC4}, /* aucMagicNumber */
   (osuint16)((((sizeof(osConfigBlock)) & 0xFF) << 8)|
              (( sizeof(osConfigBlock))         >> 8)), /* Length (little endian) */
   9,
   osdVrmMajRelNumRef,    /* MajorVersion */
   osdVrmMinRelNumRef,    /* MinorVersion */
   (osuint16)3,           /* ConfigBlockVersion */
   (osuint16)1, /* UserConfigVersion */
   /* cargo --------------------------------------------------------------- */
   &osConfigBlock,
   /* start addresses of sub-containers (fixed number) */
   &(osConfigBlock.uiNumberOfTasks),        /* Sub-Container 0 */
   (osConfigBlock.aulTaskStartAddress),     /* Sub-Container 1 */
   (osConfigBlock.aucTaskPreemptive),       /* Sub-Container 2 */
   (osConfigBlock.aucTaskTrusted),          /* Sub-Container 3 */
   (osConfigBlock.aulTaskStackStartAddress),/* Sub-Container 4 */
   (osConfigBlock.aulTaskStackEndAddress),  /* Sub-Container 5 */
   (osConfigBlock.acTaskToAppl),            /* Sub-Container 6 */
   (osConfigBlock.aucIsrTrusted),           /* Sub-Container 7 */
   (osConfigBlock.acIsrToAppl),             /* Sub-Container 8 */
   (osConfigBlock.applTrusted),             /* Sub-Container 9 */
   (osConfigBlock.trustedFunctions),        /* Sub-Container 10 */
   (osConfigBlock.nonTrustedFunctions),     /* Sub-Container 11 */
   (osConfigBlock.cat2IsrStartAddress),     /* Sub-Container 12 */
   (osConfigBlock.IsrNestable),             /* Sub-Container 13 */
   (osConfigBlock.ProcessToCore),           /* Sub-Container 14 */
   (osConfigBlock.AlarmToCore),             /* Sub-Container 15 */
   (osConfigBlock.ResourceToCore),          /* Sub-Container 16 */
   (osConfigBlock.CounterToCore),           /* Sub-Container 17 */
   (osConfigBlock.ScheduleTableToCore),     /* Sub-Container 18 */
   (osConfigBlock.ApplicationToCore),       /* Sub-Container 19 */
   (osConfigBlock.TrustedFunctionToCore),   /* Sub-Container 20 */
   (osConfigBlock.NonTrustedFunctionToCore),/* Sub-Container 21 */
   (osConfigBlock.CcbAddress),              /* Sub-Container 22 */
   (osConfigBlock.peripheralRegions),       /* Sub-Container 23 */
   (osConfigBlock.SpinlockLockMethods),     /* Sub-Container 24 */
   (osConfigBlock.SpinlockLockTypes),       /* Sub-Container 25 */
   (osConfigBlock.OptimizedSpinlockVars),   /* Sub-Container 26 */
   (osConfigBlock.osCat2IsrStacks),         /* Sub-Container 27 */
   (osConfigBlock.osIsrChannel),            /* Sub-Container 28 */
   (osConfigBlock.osIsrPrioLevel),          /* Sub-Container 29 */
   (osConfigBlock.osIsrToCore),             /* Sub-Container 30 */
   /* Sub-Container 0 */
   osdNumberOfAllTasks,
   osdNumberOfCat2ISRs,
   osdNumberOfTrustedFunctions,
   0,
   osdNumberOfApplications,
   0,
   osdStackUsageMeasurement,
   osdNumberOfAlarms,
   osdNumberOfAllResources,
   osdNumberOfAvailableCores,
   osdNumberOfCounters,
   osdNumberOfProcesses,
   osdNumberOfScheduleTables,
   0,

   {
      {(osStackPtrType)osdSystemStack_c0_BOT, (osStackPtrType)osdSystemStack_c0_TOP},
   },

   /* Sub-Container 1, task start addresses */
   {       
      &BasicTaskEntry,		
      &BasicTaskEntry,
      /*&BasicTaskEntry,*/
      &ExtendTaskEntry,
      &BasicTaskEntry,
      /*&BasicTaskEntry,*/
      &ExtendTaskEntry,
      &BasicTaskEntry,
      &InitTaskEntry,
       /*
      &SystemSwitchHighfunc,
      &FastCyclicfunc,
      &EventTaskfunc,
      &SlowCyclicfunc,
      &SlowJobfunc,
      &SystemSwitchLowfunc,
      &ResetTaskfunc,
      */
      (osTaskFctType)0
   },
   /* Sub-Container 2, task preemptiveness */
   {
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      0
   },
   /* Sub-Container 3, task trusted */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
   },
   /* Sub-Container 4, stack start address */
   {
      (osStackPtrType)osdSystemSwitchHigh_BOT,
      (osStackPtrType)osdFastCyclic_BOT,
      (osStackPtrType)osdEventTask_BOT,
      (osStackPtrType)osdSlowCyclic_BOT,
      (osStackPtrType)osdSlowJob_BOT,
      (osStackPtrType)osdSystemSwitchLow_BOT,
      (osStackPtrType)osdResetTask_BOT,
      (osStackPtrType)0
   },
   /* Sub-Container 5, stack end addresses */
   {
      (osStackPtrType)osdSystemSwitchHigh_TOP,
      (osStackPtrType)osdFastCyclic_TOP,
      (osStackPtrType)osdEventTask_TOP,
      (osStackPtrType)osdSlowCyclic_TOP,
      (osStackPtrType)osdSlowJob_TOP,
      (osStackPtrType)osdSystemSwitchLow_TOP,
      (osStackPtrType)osdResetTask_TOP,
      (osStackPtrType)0
   },
   /* Sub-Container 6, translation table: task -> os-application */
   {
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 7, isr trusted */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,       
      0,
      0,
      0,
      0,       
      0,        
      0,
      0,
      0,
      0,      
      0,
      0,      
      0,
      0,
      0,      
      0,
      0,
      0
   },
   /* Sub-Container 8, translation table: isr -> os-application */
   {
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,      
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,   
      INVALID_OSAPPLICATION,      
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,      
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,      
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 9, is application trusted information */
   {
      0
   },
   /* Sub-Container 10, trusted functions */
   {
      0
   },
   /* Sub-Container 11, non trusted functions */
   {
      0
   },
   /* Sub-Container 12, Cat 2 ISR start addresses */
   {
      &CanIsrStatus_1func,       /* ISR_CAN1ERR */
      &CanIsrWakeup_1func,       /* ISR_CAN1REC */
      &CanIsrTx_1func,           /* ISR_CAN1TRX */
	&CanIsrGlobalStatusfunc,   /* ISR_CANGERR */
	&CanIsrRxFifofunc,   /* ISR_CANGRECC */
	&ISR_TAUB0I0func,   /* ISR_TAUB0I0 */
	&ISR_TAUD0I15func,   /* ISR_TAUD0I15 */
	&ISR_TAUJ0I0func,   /* ISR_TAUJ0I0 */
	&ISR_TAUJ1I0func,   /* ISR_TAUJ1I0 */
	&ISR_WDTA0func,   /* ISR_WDTA0 */
	&ISR_IIC0RIfunc,
	&ISR_IIC0TIfunc,
	&ISR_IIC0TEIfunc,
	&ISR_IIC0EEfunc,
	&ISR_ADCA0_INTSG1func,
	&CSIH1_Rx_handler,
	&CSIH1_Tx_handler,	
	&UART0_Tx_Handler,
	&UART0_Rx_Handler,	
	&UART0_Error_Handler,
	&ISR_OSTM0func,
	&CSIH0_Rx_handler,
	&CSIH0_Tx_handler,	
	&CSIH0_Error_handler,
	&CSIH1_Error_handler,	   
    &ISR_TAUD0I6func,   /* 26 ISR_TAUD0I1 */
    &ISR_TAUJ1I2func,   /* 27 ISR_TAUD0I2 */
    &ISR_INTP6_Handler, /* 28 INTP2 */
    &ISR_TAUD0I2_handler,   /* 29 TAUB0I5*/
	&UART3_Tx_Handler,
	&UART3_Rx_Handler,  
	&UART3_Error_Handler,
	&ISR_INTP3_Handler,
	&ISR_TAUB0I11func,
   &UART2_Tx_Handler,       //35
	&UART2_Rx_Handler,       //36
	&UART2_Error_Handler,    //37
	(osIsrFctType)0
   },
   /* Sub-Container 13, Cat 2 ISR nestable */
   {
      osdFALSE, /* ISR_CAN0ERR */
      osdFALSE, /* ISR_CAN0REC */
      osdFALSE, /* ISR_CAN0TRX */
      osdFALSE, /* ISR_CANGERR */
      osdFALSE, /* ISR_CANGRECC */
      osdFALSE, /* ISR_TAUB0I0 */
      osdFALSE, /* ISR_TAUD0I */
      osdFALSE, /* ISR_TAUJ0I0 */
      osdFALSE, /* ISR_TAUJ1I0 */
      osdFALSE, /* ISR_WDTA0 */
      osdFALSE,
      osdFALSE,
      osdFALSE,
      osdFALSE,
      osdFALSE,
      osdFALSE,            
      osdFALSE,
      osdFALSE,
      osdFALSE,
      osdFALSE,
      osdFALSE,      
      osdFALSE,      
      osdFALSE,
      osdFALSE,
      osdFALSE,      
      osdFALSE, 
      osdFALSE, 
      osdFALSE, 
      osdFALSE,         
      osdFALSE,      
      osdFALSE, 
      osdFALSE,       
      osdFALSE,
      osdFALSE,
      osdFALSE,       
      osdFALSE,
      osdFALSE,
      (osuint8)0
   },
   /* Sub-Container 14, ProcessToCore */
   {
      0U, /* TASK SystemSwitchHigh */
      0U, /* TASK SystemSwitchHigh */
      0U, /* TASK FastCyclic */
      0U, /* TASK EventTask */
      0U, /* TASK SlowCyclic */
      0U, /* TASK SlowJob */
      0U, /* TASK SystemSwitchLow */
      0U, /* TASK ResetTask */
      0U, /* ISR ISR_CAN0ERR (Category = 2) */
      0U, /* ISR ISR_CAN0REC (Category = 2) */
      0U, /* ISR ISR_CAN0TRX (Category = 2) */
      0U, /* ISR ISR_CANGERR (Category = 2) */
      0U, /* ISR ISR_CANGRECC (Category = 2) */
      0U, /* ISR ISR_TAUB0I0 (Category = 2) */
      0U, /* ISR ISR_TAUD0I0 (Category = 2) */
      0U, /* ISR ISR_TAUJ0I0 (Category = 2) */
      0U, /* ISR ISR_TAUJ1I0 (Category = 2) */
      0U, /* ISR ISR_WDTA0 (Category = 2) */
      0U,
      0U,
      0U,
      0U,
      0U,
	  0U,
      0U,            
      0U,
      0U,
      0U,
      0U,          
      0U,                        
      0U,              
      0U,
      0U,          
      0U,                        
      0U,       
      0U,                        
      0U,             
	  0U,						 
	  0U,
	  0U,
	  0U,
     0U,
	  0U,
	  0U,
      (CoreIdType)0
   },
   /* Sub-Container 15, AlarmToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 16, ResourceToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 17, CounterToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 18, ScheduleTableToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 19, ApplicationToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 20, TrustedFunctionToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 21, NonTrustedFunctionToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 22, Core Control Block addresses */
   {
      &osCtrlVarsCore0,
      (osCtrlVarType*)0
   },
   /* Sub-Container 23, peripheral regions */
   {
      0
   },
   /* Sub-Container 24, Spinlock lock method */
   {
      (osuint8)0
   },
   /* Sub-Container 25, Spinlock lock type */
   {
      (osuint8)0
   },
   /* Sub-Container 26, Optimized Spinlock variables */
   {
      (osMiniLockType*) osdNULL
   },
   /* Sub-Container 27 ISR stack information */
   {
      {
         (osStackPtrType)osdISR_CAN0ERR_BOT,
         (osStackPtrType)osdISR_CAN0ERR_TOP
      },
      {
         (osStackPtrType)osdISR_CAN0ERR_BOT,
         (osStackPtrType)osdISR_CAN0ERR_TOP
      },
      {
         (osStackPtrType)osdISR_CAN0REC_BOT,
         (osStackPtrType)osdISR_CAN0REC_TOP
      },
      {
         (osStackPtrType)osdISR_CAN0TRX_BOT,
         (osStackPtrType)osdISR_CAN0TRX_TOP
      },
      {
         (osStackPtrType)osdISR_CANGERR_BOT,
         (osStackPtrType)osdISR_CANGERR_TOP
      },
      {
         (osStackPtrType)osdISR_CANGRECC_BOT,
         (osStackPtrType)osdISR_CANGRECC_TOP
      },
      {
         (osStackPtrType)osdISR_TAUB0I0_BOT,
         (osStackPtrType)osdISR_TAUB0I0_TOP
      },
      {
         (osStackPtrType)osdISR_TAUD0I0_BOT,
         (osStackPtrType)osdISR_TAUD0I0_TOP
      },
      {
         (osStackPtrType)osdISR_TAUJ0I0_BOT,
         (osStackPtrType)osdISR_TAUJ0I0_TOP
      },
      {
         (osStackPtrType)osdISR_TAUJ1I0_BOT,
         (osStackPtrType)osdISR_TAUJ1I0_TOP
      },
      {
         (osStackPtrType)osdISR_WDTA0_BOT,
         (osStackPtrType)osdISR_WDTA0_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },      
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },          
            {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },     
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },          
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },    
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },     
      {
         (osStackPtrType)osdISR_ADD_BOT,
         (osStackPtrType)osdISR_ADD_TOP
      },    
	  {
		 (osStackPtrType)osdISR_ADD_BOT,
		 (osStackPtrType)osdISR_ADD_TOP
	  },	   
	  {
		 (osStackPtrType)osdISR_ADD_BOT,
	     (osStackPtrType)osdISR_ADD_TOP
	  },
	  {
	  	 (osStackPtrType)osdISR_ADD_BOT,
	  	 (osStackPtrType)osdISR_ADD_TOP
      },      
	  {
		 (osStackPtrType)osdISR_ADD_BOT,
		 (osStackPtrType)osdISR_ADD_TOP
	  },
     {
		 (osStackPtrType)osdISR_ADD_BOT,
	     (osStackPtrType)osdISR_ADD_TOP
	  },
	  {
	  	 (osStackPtrType)osdISR_ADD_BOT,
	  	 (osStackPtrType)osdISR_ADD_TOP
      },      
	  {
		 (osStackPtrType)osdISR_ADD_BOT,
		 (osStackPtrType)osdISR_ADD_TOP
	  }, 	 
      {
         (osStackPtrType)0,
         (osStackPtrType)0
      }
   },

   /* Sub-Container 28: ISR interrupt channel index */
   {
      (osuint16) 105, /* channel of ISR_CAN1ERR */
      (osuint16) 37, /* channel of ISR_INTP10 */
      (osuint16) 107, /* channel of ISR_CAN1TRX */
      (osuint16) 14, /* channel of ISR_CANGERR */
      (osuint16) 15, /* channel of ISR_CANGRECC */
      (osuint16) 134, /* channel of ISR_TAUB0I0 */
      (osuint16) 46, /* channel of ISR_TAUD0I15 */
      (osuint16) 72, /* channel of ISR_TAUJ0I0 */
      (osuint16) 160, /* channel of ISR_TAUJ1I0 */
      (osuint16) 32, /* channel of ISR_WDTA0 */
      (osuint16) 70, 	// IIC0RI
      (osuint16) 68,	// IIC0TI
      (osuint16) 69,	//IIC0TEI
      (osuint16) 71,	//IIC0EE
      (osuint16) 10,	//ADCA0 SG1 end
      (osuint16) 109,	//ICCSIH1IR
      (osuint16) 108,	//ICCSIH1IC      
      (osuint16) 26,		// UART0 TX
      (osuint16) 27,
      (osuint16) 28,      
      (osuint16) 76,     
      (osuint16) 22,		// CSIH0 IR
      (osuint16) 21,		//CSIH0 IC
      (osuint16) 23,      	// IRE
      (osuint16) 110,      
      (osuint16) 3,   		// 26 ISR_TAUD0I6
      (osuint16) 162,    	// 27 ISR_TAUJ1I2 
      (osuint16) 120,		//28 INTP6
      (osuint16) 1,		    //29 TAUD0I2
      (osuint16) 221,       //31 UART3_Tx_Handler
      (osuint16) 222,       //32 UART3_Rx_Handler
      (osuint16) 223,       //33 UART3_Error_Handler
	  (osuint16) 34,		//33 INTP3
	  (osuint16) 145,
     (osuint16) 157,       // UART2_Tx_Handler
      (osuint16) 158,       // UART2_Rx_Handler
      (osuint16) 159,       // UART2_Error_Handler
      (osuint16) 0  /* empty */
   },

   /* Sub-Container 29: ISR interrupt priority level */
   {
      (osuint16)0x0001, /* priority level of ISR_CAN0ERR */
      (osuint16)0x0001, /* priority level of ISR_CAN0REC */
      (osuint16)0x0001, /* priority level of ISR_CAN0TRX */
      (osuint16)0x0001, /* priority level of ISR_CANGERR */
      (osuint16)0x0001, /* priority level of ISR_CANGRECC */
      (osuint16)0x0001, /* priority level of ISR_TAUB0I0 */
      (osuint16)0x0000, /* priority level of ISR_TAUD0I0 */
      (osuint16)0x0001, /* priority level of ISR_TAUJ0I0 */
      (osuint16)0x0001, /* priority level of ISR_TAUJ0I0 */
      (osuint16)0x0001, /* priority level of ISR_TAUJ1I0 */
      (osuint16)0x0001, /* priority level of ISR_WDTA0 */
      (osuint16)0x0001, 
      (osuint16)0x0001, 
      (osuint16)0x0001, 
      (osuint16)0x0001, 
      (osuint16)0x0001,        
	  (osuint16)0x0001,
      (osuint16)0x0001,    
      (osuint16)0x0001, 
      (osuint16)0x0001,        
      (osuint16)0x0001,
      (osuint16)0x0001,                
      (osuint16)0x0001,                  
      (osuint16)0x0001,        
      (osuint16)0x0001,
      (osuint16)0x0001,    
      (osuint16)0x0001,   
      (osuint16)0x0001,           
	  (osuint16)0x0001,
	  (osuint16)0x0001, 			   
	  (osuint16)0x0001,    	 
	  (osuint16)0x0001,	  
	  (osuint16)0x0001,	  
	  (osuint16)0x0001,
     (osuint16)0x0001,	  
	  (osuint16)0x0001,	  
	  (osuint16)0x0001,    	 
      (osuint16)0x0000  /* empty */
   },

   /* Sub-Container 30: ISR to Core assignment */
   {
      0U, /* ISR ISR_CAN0ERR (Category = 2) */
      0U, /* ISR ISR_CAN0REC (Category = 2) */
      0U, /* ISR ISR_CAN0TRX (Category = 2) */
      0U, /* ISR ISR_CANGERR (Category = 2) */
      0U, /* ISR ISR_CANGRECC (Category = 2) */
      0U, /* ISR ISR_TAUB0I0 (Category = 2) */
      0U, /* ISR ISR_TAUD0I0 (Category = 2) */
      0U, /* ISR ISR_TAUJ0I0 (Category = 2) */
      0U, /* ISR ISR_TAUJ1I0 (Category = 2) */
      0U, /* ISR ISR_WDTA0 (Category = 2) */
      0U, 
      0U, 
      0U, 
      0U,                               
      0U,      
      0U,                                 
      0U,                               
      0U,                               
      0U,      
      0U,                                 
      0U,                                  
      0U,                    
      0U,      
      0U,                                 
      0U,                                  
      0U,
      0U,                                  
      0U, 
      0U,                       
	  0U,
	  0U,
	  0U,	  
	  0U,
	  0U,
     0U,	  
	  0U,
	  0U,
      0U  /* empty */
   },

   (osuint32)0 /* uiCheckSum */
};

#pragma ghs section rodata=default
#pragma ghs section rosdata=default

