/* file: D:/AutoSar generated code/osStacks.c */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil */
/* Generation time: Mon May 16 10:20:54 2016 */
/* Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel */
/* Implementation: RH850_D1M */
/* Version of general code: 9.01.04 */
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel0_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel0_c0 [50]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osIntStackLevel1_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osIntStackLevel1_c0 [150]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osSystemStack_c0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osSystemStack_c0[300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack0"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack0 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack1"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack1 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack2"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack2 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack3"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack3 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack4"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack4 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack5"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack5 [300]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

#pragma ghs startdata
#pragma ghs section bss=".osTaskStack6"
#pragma alignvar(4)
/* MISRA RULE 8.10 not violated: The stack is accessed by assembly language code.
 * This is not detected by the analysis tool. */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack6 [75]; /* PRQA S 1504 */ /* PRQA S 4152 */
#pragma ghs section bss=default
#pragma ghs enddata

