/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        :
* Module        :
* Instance      :
* Description   :
 file: D:/AutoSar generated code/tcb.h 
 automatically generated by genRH850.exe, Version: 1.06 
 Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil 
 Generation time: Mon May 16 15:24:45 2016 
 Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel 
 Implementation: RH850_D1M 
 Version of general code: 9.01.04 
 MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with message 0883,
  but there is a double include prevention and therefore the message is considered to be wrong. 
*-----------------------------------------------------------------------
* Version:
* Date:
* Author:
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jan 02,2016    Initial version
*-----------------------------------------------------------------------
* 0.2	   Dec 20,2016   ShangQiuju Add config file according using hw.
*----------------------------------------------------------------------
* 0.3          Dec 21,2016    PEI Jingli    Add ds03h hw version selection.
 ----------------------------------------------------------------------
* 0.4    	   Jan 16,2017    RenWeimin  Add test code. Use TAUJ1I3 for capture.
* ----------------------------------------------------------------------
* 0.5          Feb 07,2017    ZhangJie     Change CAN ISR from channel 0 to 2.
*----------------------------------------------------------------------
* 0.6    	   Mar 22,2017    ZhangJie    Add TAUJ1I0 for system tick counter.
*----------------------------------------------------------------------
* 0.7          Apr 04,2017    PEI Jingli    Delete testing code.
*=====================================================================*/

#if ! defined __TCB_H__   /* PRQA S 0883 EOF */ 
#define __TCB_H__
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdNumberOfAlarmsOnHiResCounter 0

#define osdUseHighResolutionTimer 0

#define osdHwTimerNeeded_OSTM 0 /* 1  open OSTM	*/		
#define osdHwTimerNeeded_OSTM_HIRES 0

#define osdHardwareTimerNeeded 0 /*1	 open OSTM*/
#define osdGetCurrentTimeHighResHybridIdx -1
#define osdGetCurrentTimeHighResMonoIdx -1
#define osdGetCurrentTimeStdIdx -1
#define osdSetTIPAbsMaxGtSemiCountIdx -1
#define osdSetTIPAbsMaxLeSemiCountIdx -1
#define osdSetTIPRelMaxGtSemiCountIdx -1
#define osdSetTIPRelMaxLeSemiCountIdx -1
#define osdClearTIPAbsIdx -1
#define osdClearTIPRelIdx -1
#define osdHandleCounterInterruptHiResIdx -1
#define osdHandleCounterInterruptStdIdx -1
#define osdInsertMinHeapHiResIdx -1
#define osdInsertMinHeapStdIdx -1
#define osdORTIDebug 0
#define osdORTIVersion  not used anymore!
#define osdORTIStdVersion 210
#define osdORTIEnabled 1
#define osdNumberOfScheduleTables 0
#define osdNumberOfHiResSchedTabs 0
#define osdScheduleTableSyncUsed 0
#define osdNumberOfSTExpiryPoints 0
#define osdNumberOfSTSetEvent 0
#define osdNumberOfSTActivateTask 0
#define osdNumberOfSTEntries 0
#define osdCallTimingHooks 1
#define osdTimingHooksFileName "TimingHook.h"
#define osdRH850_F1L		/*osdRH850_D1M*/

#define osdExceptionDetails  1

#define osdRH850_FPU   0

#define ISR_CAN1ERR_index  0
#define ISR_INTP10_index  1
#define ISR_CAN1TRX_index  2
#define ISR_CANGERR_index  3
#define ISR_CANGRECC_index  4
#define ISR_TAUB0I0_index  5
#define ISR_TAUD0I15_index  6
#define ISR_TAUJ0I0_index  7
#define ISR_TAUJ1I0_index  8
#define ISR_WDTA0_index  9
#define ISR_IIC0RI_index 10
#define ISR_IIC0TI_index 11
#define ISR_IIC0TEI_index 12
#define ISR_IIC0EE_index 13
#define ISR_ADCA0_INTSG1_index 14
#define ISR_CSIH1IR_index 15
#define ISR_CSIH1IC_index 16
#define ISR_UART0_Tx_index 17
#define ISR_UART0_Rx_index 18
#define ISR_UART0_Error_index 19
#define ISR_OSTM0_index 20
#define ISR_CSIH0IR_index 21
#define ISR_CSIH0IC_index 22
#define ISR_CSIH0IRE_index 23
#define ISR_CSIH1IRE_index 24
#define ISR_TAUD0I6_index 25  /* add TAUD0I1 */
#define ISR_TAUJ1I2_index 26  /* add TAUJ0I2 */
#define ISR_INTP6_index 27
#define ISR_TAUD0I2_index 28
#define ISR_UART3_Tx_index 29
#define ISR_UART3_Rx_index 30
#define ISR_UART3_Error_index 31
#define ISR_INTP3_index	32
#define ISR_TAUB0I11_index 33
#define ISR_UART2_Tx_index 34
#define ISR_UART2_Rx_index 35
#define ISR_UART2_Error_index 36



#define osdISRHooks            0

#define osdNumberOfPrioLevels  16
#define osdNumberOfInterrupts  256

#define osdSystemLevel         0
#define osdSystemLevelMask     0x0000ffffUL
#define osdSystemStackSize     600
#define osdStackCheckPattern   0xaaaaaaaaUL

#define osdOnCore                  0
#define osdNumberOfAvailableCores  1
#define osdTimerInterruptSourceNumberCore0 125
#define CC ECC1		/*AUTO?*/
#define STATUS_LEVEL STANDARD_STATUS		/*EXTENDED_STATUS*/
#define osdAllowAccessNotUsed 
#define osdByteSize 8U
#define osdCallTrustedFunctionNotUsed 
#define osdCancelAlarmNotUsed 
#define osdCheckISRMemoryAccessNotUsed 
#define osdCheckObjectAccessNotUsed 
#define osdCheckObjectOwnershipNotUsed 
#define osdCheckTaskMemoryAccessNotUsed 
#define osdCompiler osdCompilerGHSRH850
#define osdFullPreempt 1
#define osdGetAlarmBaseNotUsed 
#define osdGetAlarmNotUsed 
#define osdGetApplicationStateNotUsed 
#define osdGetCounterValueNotUsed 
#define osdGetElapsedValueNotUsed 
#define osdGetResourceNotUsed 
#define osdGetScheduleTableStatusNotUsed 
#define osdIncrementCounterNotUsed 
#define osdLib 0
#define osdMixedPreempt 0
#define osdNeedIOCTypes 0
#define osdNextScheduleTableNotUsed 
#define osdNonPreempt 0
#define osdNumApplErrorHooks 0
#define osdNumApplShutdownHooks 0
#define osdNumApplStartupHooks 0
#define osdNumberOfAllResources 0
#define osdNumberOfBasicTasks 1
#define osdNumberOfExtendedTasks 6
#define osdNumberOfIOCCommunications 0
#define osdNumberOfInternalResources 0
#define osdNumberOfInterruptResources 0
#define osdNumberOfPriorities 7
#define osdNumberOfQueuedIOCCallbacks 0
#define osdNumberOfQueuedIOCCommunications 0
#define osdNumberOfSemaphores 0
#define osdNumberOfTaskResources 0
#define osdRTSize 1
#define osdReducedStatusChecks 0
#define osdReleaseResourceNotUsed 
#define osdResAccessMaskBits 32
#define osdSC SC1
#define osdSetAbsAlarmNotUsed 
#define osdSetRelAlarmNotUsed 
#define osdSetScheduleTableAsyncNotUsed 
#define osdStartScheduleTableAbsNotUsed 
#define osdStartScheduleTableRelNotUsed 
#define osdStartScheduleTableSynchronNotUsed 
#define osdStopScheduleTableNotUsed 
#define osdSyncScheduleTableNotUsed 
#define osdSysErrorHook 0
#define osdSysShutdownHook 0
#define osdSysStartupHook 0
#define osdTimingProtectionUsed 0
#define osdUseIOC 0
#define osdosGetISRMaxBlockingTimeNotUsed 
#define osdosGetISRMaxExecutionTimeNotUsed 
#define osdosGetISRMinInterArrivalTimeNotUsed 
#define osdosGetTaskMaxBlockingTimeNotUsed 
#define osdosGetTaskMaxExecutionTimeNotUsed 
#define osdosGetTaskMinInterArrivalTimeNotUsed 


#define osdNumberOfAllISRs  37
#define osdNumberOfAllTasks 7
#define osdNumberOfCat1ISRs 0
#define osdNumberOfCat2ISRs 37


#define osdNumberOfTrustedFunctions 0
#define osdUseTrustedFunctionStubs 0
#define osdNumberOfAlarms 0
#define osdNumberOfAlarmCallback 0
#define osdNumberOfAlarmSetEvent 0
#define osdNumberOfAlarmActivateTask 0
#define osdNumberOfAlarmIncrementCounter 0
#define osdNumberOfCounters 0
#define osdNumberOfSWCounters 0
#define osdNumberOfSWAndSRCounters 0
#define osdNumberOfApplications 0
#define osdStackCheck 1
#define osdStackUsageMeasurement 1

#define osdTypeHeaderInclude 1

#define osdEnableAssertions 1

#define osdGetServiceIdMacros 0
#define osdParameterAccessMacros 0

#define osdTimingMeasurement 0
#define osdProtectAndMeasureAll 0
#define osdAsSelected 0
#define osdOnlyMeasureAll 0

#define osdProtReactKillTaskIsrAllowed  0
#define osdProtReactKillApplAllowed     0
#define osdProtReactKillApplRestAllowed 0
#define osdErrorHook 0
#define osdPreTaskHook 0
#define osdPostTaskHook 0
#define osdShutdownHook 0
#define osdProtectionHook 0

#if osdProtectionHook

 #if (osdTimingProtectionUsed && osdProtReactKillTaskIsrAllowed)
  #define osdKillTaskIsrPossible 1
 #endif /*(osdTimingProtectionUsed && osdProtReactKillTaskIsrAllowed)*/

 #if ((osdSC == SC4) && (defined osdTimingProtectionUsed) && (osdProtReactKillApplAllowed || osdProtReactKillApplRestAllowed))
  #ifndef osdKillTaskIsrPossible
   #define osdKillTaskIsrPossible 1
  #endif
  #define osdKillApplPossible 1
 #endif /* (osdSC == SC4) && (defined osdTimingProtectionUsed) && (osdProtReactKillApplAllowed || osdProtReactKillApplRestAllowed))*/

#endif /* osdProtectionHook */

#if ((osdSC == SC3) || (osdSC == SC4)) && (!defined osdTerminateApplicationNotUsed)
 #ifndef osdKillTaskIsrPossible /* prevent from double-definition */
  #define osdKillTaskIsrPossible 1
 #endif
 #ifndef osdKillApplPossible
  #define osdKillApplPossible 1
 #endif
#endif /* ((osdSC == SC3) || (osdSC == SC4)) */

#ifndef osdKillTaskIsrPossible
 #define osdKillTaskIsrPossible 0
#endif

#ifndef osdKillApplPossible
 #define osdKillApplPossible 0
#endif

#define osdNumberOfProcesses (osdNumberOfAllTasks+osdNumberOfCat2ISRs)

#endif /* ! defined __TCB_H__ */
