/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        : IO_System_if.h
* Module        :
* Instance      :
* Description   :
*-----------------------------------------------------------------------
* Version:  0.1
* Date: 2011-11-24
* Author: Shao Guangxian
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
* ----------------------------------------------------------------------
* 0.1  Apr 15,2016                Initial version.  
*------------------------------------------------------------------------
* 0.2 Jan 24,2017  ZhangJie  Fix Coverity warnings.
*=====================================================================*/
#ifndef _IOSYSTEM_H_
#define _IOSYSTEM_H_

#include "CONFIG.H"
#include "TYPES.H"   
#include "ADC_APP.h"
#include "GPIO_APP.h"
/*#include  PROJECT_MCU_CONFIG_FILE*/
/**** Definition of constants ****/



/**** Declaration of constants ****/


/**** Declaration of variables ****/


/**** Declaration of functions ****/
#endif /*_IOSYSTEM_H_*/
